const fs=require('node:fs'); const path=require('node:path'); const vm=require('node:vm'); const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const noop=()=>{}; const element={value:'',hidden:false,classList:{add:noop,remove:noop,toggle:noop},addEventListener:noop,setAttribute:noop};
const memory=new Map();
const context=vm.createContext({console,TextEncoder,TextDecoder,URL,URLSearchParams,btoa,atob,crypto:require('node:crypto').webcrypto,document:{querySelector:()=>element,querySelectorAll:()=>[],addEventListener:noop,documentElement:{classList:element.classList},body:{classList:element.classList}},window:{addEventListener:noop},location:{search:'',hash:''},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},setTimeout:()=>0,clearTimeout:noop,requestAnimationFrame:noop,alert:noop});
for(const f of ['js/exercise-catalog.js','js/equipment-catalog.js','js/translations.js','js/routine-engine.js','js/sharing.js','js/tracking.js','app.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context,{filename:f});
const run=s=>vm.runInContext(s,context); const base={id:'test',name:'QA בן בנימין',age:35,height:175,weight:80,gender:'male',experience:'new',days:3,duration:60,goal:'general',activity:'moderate',cardioPreference:'any',issues:[],issueNotes:'PRIVATE ISSUE',trainerNotes:'PRIVATE STAFF',memberNotes:'Public note',memberNotesHe:'הערה למתאמן'};
context.base=base;context.assert=assert;
run(`let count=0;for(const goal of ['general','fatloss','muscle','strength'])for(const experience of ['new','some','experienced'])for(const days of [2,3,4,5])for(const duration of [30,45,60,75])for(let mask=0;mask<64;mask++){const issues=Object.keys(ISSUE_LABEL).filter((_,i)=>mask&(1<<i));const p={...base,goal,experience,days,duration,issues};const plan=buildPlan(p);assert.equal(plan.workouts.length,days);for(const w of plan.workouts){assert(w.exercises.length>=3);assert.equal(new Set(w.exercises.map(x=>x.key)).size,w.exercises.length);for(const ex of w.exercises){assert(EX[ex.key]);assert.equal(safeExercise(ex.key,p).key,ex.key);assert(ex.sets>=1&&ex.sets<=4);assert(EQUIPMENT_ASSETS[ex.equipmentType]||EQUIPMENT_ASSETS.machine);}}count++;}console.log('PASS '+count+' generated combinations (all limitation combinations, goals, experience, days and durations)');`);
run(`currentPlan=buildPlan(base); currentLanguage='he';const original={...currentPlan.workouts[0].exercises[0]};applyExerciseSwap(0,0,'gobletSquat');Object.assign(currentPlan.workouts[0].exercises[0],{sets:3,reps:'10–12',rest:'75 sec',note:'QA cue',noteHe:'הנחיה לבדיקה'});const publicPlan=publicSharePlan(currentPlan);const payload=JSON.stringify(publicPlan);for(const secret of ['PRIVATE ISSUE','PRIVATE STAFF','\"height\":','\"weight\":','\"gender\":','lowBack','issueNotes','trainerNotes'])assert(!payload.includes(secret),secret);const shared=inflateSharedPlan(decodeShare(encodeShare(publicPlan)));assert.equal(shared.sharedLanguage,'he');assert.equal(shared.workouts[0].exercises[0].noteHe,'הנחיה לבדיקה');assert.equal(shared.workouts[0].exercises[0].rest,'75 sec');assert.equal(shared.profile.memberNotes,'Public note');assert.equal(shared.warmup,currentPlan.warmup);const saved={...base,routineOverride:serializeRoutineState(currentPlan)};validateProfiles([saved]);const restored=restoreRoutineState(saved);assert.equal(restored.workouts[0].exercises[0].note,'QA cue');currentPlan=restored;resetExerciseToGenerated(0,0);assert.equal(currentPlan.workouts[0].exercises[0].key,original.key);assert.equal(currentPlan.workouts[0].exercises[0].sets,original.sets);assert.equal(formatHebrewMeasure('20–30 sec/side'),'20–30 שנ׳ לכל צד');console.log('PASS edit/save/restore/reset/share round trips, bilingual notes and privacy');`);
run(`for(const bad of [null,{}, {profile:{},workouts:[]}, {profile:base,workouts:[{name:'bad',nameHe:'bad',exercises:[{key:'<script>',sets:2,reps:'8',rest:'60'}]}]}]) assert.throws(()=>inflateSharedPlan(bad));assert.throws(()=>decodeShare('!bad'));assert.throws(()=>validateProfiles({}));assert.throws(()=>validateProfiles([{...base,issues:'wrong'}]));assert.throws(()=>validateProfiles([base,base]));const light=buildPlan({...base,weight:40});const heavy=buildPlan({...base,weight:200});assert.equal(JSON.stringify(light.workouts),JSON.stringify(heavy.workouts));console.log('PASS corrupt input rejection and no bodyweight-based prescriptions');`);
for(const file of fs.readdirSync(path.join(root,'assets/equipment')))assert(fs.statSync(path.join(root,'assets/equipment',file)).size>100);
console.log('All regression checks passed.');

const functionNames=new Set();for(const file of ['app.js',...fs.readdirSync(path.join(root,'js')).map(f=>'js/'+f)]){for(const match of fs.readFileSync(path.join(root,file),'utf8').matchAll(/(?:async )?function ([A-Za-z0-9_]+)\(/g)){assert(!functionNames.has(match[1]),'Duplicate function: '+match[1]);functionNames.add(match[1]);}}console.log('PASS unique function definitions across all scripts');

run(`const v4=publicSharePlan(buildPlan(base));const v3={...v4,v:3,p:{...v4.p,a:'moderate'},w:v4.w.map(w=>({...w,x:w.x.map(x=>x.slice(0,7))}))};assert.equal(inflateSharedPlan(v3).workouts.length,3);const v2=normalizeSharedPlan(v3);assert.equal(inflateSharedPlan(v2).workouts[0].exercises[0].key,'legPress');setProfiles([base]);assert.equal(getProfiles()[0].name,base.name);assert.equal(routineText('6–10'),'<bdi dir="ltr">6–10</bdi>');console.log('PASS legacy v2/v3 links, local storage round trip and bidi ranges');`);

// Inventory mappings must remain local, traceable and specific to the equipment.
const inventory=JSON.parse(fs.readFileSync(path.join(root,'assets/equipment/inventory.json'),'utf8'));
assert.equal(inventory.items.length,26);
assert.equal(new Set(inventory.items.map(x=>x.id)).size,26);
for(const item of inventory.items){assert(item.src.startsWith('./assets/equipment/'));assert(fs.existsSync(path.join(root,item.src)));assert(item.quantity>0);assert(item.sourcePage>=1&&item.sourcePage<=3);}
assert.equal(inventory.items.find(x=>x.id==='smith-machine').status,'optional');
context.inventoryItems=inventory.items;
run(`for(const ex of Object.values(EX)){const asset=equipmentAsset(ex);assert(asset.src.startsWith('./assets/equipment/'));if(asset.kind==='photo'){const source=inventoryItems.find(x=>x.id===asset.inventoryId);assert(source);assert.equal(source.src,asset.src);assert.equal(source.status,'listed');}}assert.equal(equipmentAsset(EX.row).inventoryId,'seated-row');assert.equal(equipmentAsset(EX.pulldown).inventoryId,'lat-pulldown');assert.equal(equipmentAsset(EX.cableCurl).inventoryId,'functional-trainer');for(const key of ['bike','rower','legCurl','hackSquat','stepUp','deadBug','neutralPress','calf'])assert.equal(equipmentAsset(EX[key]).kind,'drawing');console.log('PASS inventory provenance, exact image mappings and pending-equipment fallbacks');`);

run(`for(const [reps,expected] of [['8','60 sec'],['8–12','60 sec'],['10–15','60 sec'],['6','90–120 sec'],['4–6','90–120 sec'],['5–8','90–120 sec'],['6–10','90–120 sec'],['7','60 sec'],['20–30 sec','60 sec']])assert.equal(restRange(base,'main',reps),expected);assert.equal(exerciseRow('row',base,'main',{reps:'6'}).rest,'90–120 sec');assert.equal(exerciseRow('row',base,'main',{reps:'8',rest:'75 sec'}).rest,'75 sec');for(const goal of ['general','fatloss','muscle','strength']){const plan=buildPlan({...base,goal});for(const workout of plan.workouts)for(const ex of workout.exercises)if(!['balance','cardio'].includes(ex.role))assert.equal(ex.rest,restRange(base,ex.role,ex.reps));}const ropeProfile={...base,goal:'fatloss',duration:60,cardioPreference:'jumpRope'};const ropePlan=buildPlan(ropeProfile);assert(ropePlan.workouts.every(w=>w.exercises.some(ex=>ex.key==='jumpRope'&&ex.note.includes('intervals'))));for(const issue of ['knee','hip','lowBack'])assert.equal(chooseCardio({...ropeProfile,issues:[issue]}).key,'bike');currentPlan=ropePlan;const ropeSaved={...ropeProfile,routineOverride:serializeRoutineState(ropePlan)};validateProfiles([ropeSaved]);assert(restoreRoutineState(ropeSaved).workouts[0].exercises.some(x=>x.key==='jumpRope'));assert(inflateSharedPlan(decodeShare(encodeShare(publicSharePlan(ropePlan)))).workouts[0].exercises.some(x=>x.key==='jumpRope'));assert(SWAP_FAMILIES.some(group=>group.includes('treadmill')&&group.includes('jumpRope')));console.log('PASS rep-based rest defaults, explicit overrides, jump-rope selection, substitutions and saved/shared round trips');`);

run(`const logA=buildPlan({...base,id:'member-a'});const logB=buildPlan({...base,id:'member-b'});assert.notEqual(trackingIdentity(logA),trackingIdentity(logB));assert.equal(trackingIdentity(inflateSharedPlan(publicSharePlan(logA))),trackingIdentity(logA));const entry={id:'session-1',date:'2026-09-15',created:123,exercise:'chestPress',day:0,sets:[{kg:25,result:'10'},{kg:'',result:'30 sec'}]};writeWorkoutLogs(trackingIdentity(logA),[entry]);assert.equal(readWorkoutLogs(trackingIdentity(logA))[0].sets[0].kg,25);assert.equal(readWorkoutLogs(trackingIdentity(logB)).length,0);assert.equal(mergeWorkoutLogs([entry],[entry]).length,1);assert.throws(()=>mergeWorkoutLogs([entry],[{...entry,sets:[{kg:30,result:'10'}]}]));for(const bad of [{...entry,date:'2026-02-31'},{...entry,sets:[]},{...entry,exercise:'unknown'},{...entry,sets:[{kg:-5,result:'10'}]},{...entry,sets:[{kg:10,result:''}]}])assert.throws(()=>validateWorkoutLogs([bad]));assert(!JSON.stringify(publicSharePlan(logA)).includes('session-1'));assert.equal(restSeconds('90–120 sec'),120);assert.equal(restSeconds('2–3 min'),180);assert.equal(restSeconds('—'),60);assert.equal(timerRemaining({deadline:10000,remaining:60},1000),9);assert.equal(timerRemaining({deadline:10000,remaining:60},15000),0);assert.equal(timerRemaining({deadline:0,remaining:35},15000),35);console.log('PASS log isolation, share identity, storage, duplicate/conflict handling, validation, privacy and elapsed-time timer');`);
